#!/bin/bash
# Auto-generated by linkedin-clay-sync
# Runs every morning — scrapes LinkedIn and pushes new connections to Clay

LOG="/tmp/linkedin-clay-sync.log"
CLI="$(dirname "$0")/../src/cli.ts"

# Read webhook URL from saved config (~/.linkedin-clay-sync.json)
WEBHOOK=$(node -e "
try {
  const c = require(process.env.HOME + '/.linkedin-clay-sync.json');
  process.stdout.write(c.clayWebhookUrl || '');
} catch(e) {}
" 2>/dev/null)

# Fall back to environment variable
if [ -z "$WEBHOOK" ]; then
  WEBHOOK="${CLAY_WEBHOOK_URL:-}"
fi

if [ -z "$WEBHOOK" ]; then
  echo "$(date): ERROR — No Clay webhook URL configured. Run: npm run scrape -- --webhook YOUR_URL" >> "$LOG"
  exit 1
fi

echo "$(date): Starting daily LinkedIn→Clay sync" >> "$LOG"
npx tsx "$CLI" scrape --webhook "$WEBHOOK" >> "$LOG" 2>&1
echo "$(date): Done" >> "$LOG"
